<?php
namespace __Dev5\BasicOpenCart;

/**
 * @package   Basic OpenCart AutoComplete for PHPStorm
 * @version   1.1
 * @author    Vitor Reis - Loja Dev5™
 * @link      https://dev5.com.br
 *
 * @property \Admin\ModelCatalogAttribute $model_catalog_attribute
 * @property \Admin\ModelCatalogAttributeGroup $model_catalog_attribute_group
 * @property \Admin\ModelCatalogCategory|\Catalog\ModelCatalogCategory $model_catalog_category
 * @property \Admin\ModelCatalogDownload $model_catalog_download
 * @property \Admin\ModelCatalogFilter $model_catalog_filter
 * @property \Admin\ModelCatalogInformation|\Catalog\ModelCatalogInformation $model_catalog_information
 * @property \Admin\ModelCatalogManufacturer|\Catalog\ModelCatalogManufacturer $model_catalog_manufacturer
 * @property \Admin\ModelCatalogOption $model_catalog_option
 * @property \Admin\ModelCatalogProduct|\Catalog\ModelCatalogProduct $model_catalog_product
 * @property \Admin\ModelCatalogRecurring $model_catalog_recurring
 * @property \Admin\ModelCatalogReview|\Catalog\ModelCatalogReview $model_catalog_review
 * @property \Admin\ModelCustomerCustomField $model_customer_custom_field
 * @property \Admin\ModelCustomerCustomer $model_customer_customer
 * @property \Admin\ModelCustomerCustomerApproval $model_customer_customer_approval
 * @property \Admin\ModelCustomerCustomerGroup $model_customer_customer_group
 * @property \Admin\ModelDesignBanner|\Catalog\ModelDesignBanner $model_design_banner
 * @property \Admin\ModelDesignLayout|\Catalog\ModelDesignLayout $model_design_layout
 * @property \Admin\ModelDesignSeoUrl $model_design_seo_url
 * @property \Admin\ModelDesignTheme|\Catalog\ModelDesignTheme $model_design_theme
 * @property \Admin\ModelDesignTranslation|\Catalog\ModelDesignTranslation $model_design_translation
 * @property \Admin\ModelExtensionAdvertiseGoogle|\Catalog\ModelExtensionAdvertiseGoogle $model_extension_advertise_google
 * @property \Admin\ModelExtensionDashboardActivity $model_extension_dashboard_activity
 * @property \Admin\ModelExtensionDashboardChart $model_extension_dashboard_chart
 * @property \Admin\ModelExtensionDashboardMap $model_extension_dashboard_map
 * @property \Admin\ModelExtensionDashboardOnline $model_extension_dashboard_online
 * @property \Admin\ModelExtensionDashboardSale $model_extension_dashboard_sale
 * @property \Admin\ModelExtensionFeedGoogleBase|\Catalog\ModelExtensionFeedGoogleBase $model_extension_feed_google_base
 * @property \Admin\ModelExtensionFraudFraudlabspro|\Catalog\ModelExtensionFraudFraudlabspro $model_extension_fraud_fraudlabspro
 * @property \Admin\ModelExtensionFraudIp|\Catalog\ModelExtensionFraudIp $model_extension_fraud_ip
 * @property \Admin\ModelExtensionFraudMaxmind|\Catalog\ModelExtensionFraudMaxmind $model_extension_fraud_maxmind
 * @property \Admin\ModelExtensionModulePaypalSmartButton|\Catalog\ModelExtensionModulePaypalSmartButton $model_extension_module_paypal_smart_button
 * @property \Admin\ModelExtensionPaymentAmazonLoginPay|\Catalog\ModelExtensionPaymentAmazonLoginPay $model_extension_payment_amazon_login_pay
 * @property \Admin\ModelExtensionPaymentBluepayHosted|\Catalog\ModelExtensionPaymentBluepayHosted $model_extension_payment_bluepay_hosted
 * @property \Admin\ModelExtensionPaymentBluepayRedirect|\Catalog\ModelExtensionPaymentBluepayRedirect $model_extension_payment_bluepay_redirect
 * @property \Admin\ModelExtensionPaymentCardconnect|\Catalog\ModelExtensionPaymentCardconnect $model_extension_payment_cardconnect
 * @property \Admin\ModelExtensionPaymentCardinity|\Catalog\ModelExtensionPaymentCardinity $model_extension_payment_cardinity
 * @property \Admin\ModelExtensionPaymentDivido|\Catalog\ModelExtensionPaymentDivido $model_extension_payment_divido
 * @property \Admin\ModelExtensionPaymentEway|\Catalog\ModelExtensionPaymentEway $model_extension_payment_eway
 * @property \Admin\ModelExtensionPaymentFirstdata|\Catalog\ModelExtensionPaymentFirstdata $model_extension_payment_firstdata
 * @property \Admin\ModelExtensionPaymentFirstdataRemote|\Catalog\ModelExtensionPaymentFirstdataRemote $model_extension_payment_firstdata_remote
 * @property \Admin\ModelExtensionPaymentG2apay|\Catalog\ModelExtensionPaymentG2apay $model_extension_payment_g2apay
 * @property \Admin\ModelExtensionPaymentGlobalpay|\Catalog\ModelExtensionPaymentGlobalpay $model_extension_payment_globalpay
 * @property \Admin\ModelExtensionPaymentGlobalpayRemote|\Catalog\ModelExtensionPaymentGlobalpayRemote $model_extension_payment_globalpay_remote
 * @property \Admin\ModelExtensionPaymentKlarnaCheckout|\Catalog\ModelExtensionPaymentKlarnaCheckout $model_extension_payment_klarna_checkout
 * @property \Admin\ModelExtensionPaymentLaybuy|\Catalog\ModelExtensionPaymentLaybuy $model_extension_payment_laybuy
 * @property \Admin\ModelExtensionPaymentPaypal|\Catalog\ModelExtensionPaymentPaypal $model_extension_payment_paypal
 * @property \Admin\ModelExtensionPaymentPilibaba|\Catalog\ModelExtensionPaymentPilibaba $model_extension_payment_pilibaba
 * @property \Admin\ModelExtensionPaymentPpBraintree|\Catalog\ModelExtensionPaymentPpBraintree $model_extension_payment_pp_braintree
 * @property \Admin\ModelExtensionPaymentPpExpress|\Catalog\ModelExtensionPaymentPpExpress $model_extension_payment_pp_express
 * @property \Admin\ModelExtensionPaymentPpPayflowIframe|\Catalog\ModelExtensionPaymentPpPayflowIframe $model_extension_payment_pp_payflow_iframe
 * @property \Admin\ModelExtensionPaymentPpProIframe|\Catalog\ModelExtensionPaymentPpProIframe $model_extension_payment_pp_pro_iframe
 * @property \Admin\ModelExtensionPaymentRealex|\Catalog\ModelExtensionPaymentRealex $model_extension_payment_realex
 * @property \Admin\ModelExtensionPaymentRealexRemote|\Catalog\ModelExtensionPaymentRealexRemote $model_extension_payment_realex_remote
 * @property \Admin\ModelExtensionPaymentSagepayDirect|\Catalog\ModelExtensionPaymentSagepayDirect $model_extension_payment_sagepay_direct
 * @property \Admin\ModelExtensionPaymentSagepayServer|\Catalog\ModelExtensionPaymentSagepayServer $model_extension_payment_sagepay_server
 * @property \Admin\ModelExtensionPaymentSecuretradingPp|\Catalog\ModelExtensionPaymentSecuretradingPp $model_extension_payment_securetrading_pp
 * @property \Admin\ModelExtensionPaymentSecuretradingWs|\Catalog\ModelExtensionPaymentSecuretradingWs $model_extension_payment_securetrading_ws
 * @property \Admin\ModelExtensionPaymentSquareup|\Catalog\ModelExtensionPaymentSquareup $model_extension_payment_squareup
 * @property \Admin\ModelExtensionPaymentWorldpay|\Catalog\ModelExtensionPaymentWorldpay $model_extension_payment_worldpay
 * @property \Admin\ModelExtensionReportActivity $model_extension_report_activity
 * @property \Admin\ModelExtensionReportCoupon $model_extension_report_coupon
 * @property \Admin\ModelExtensionReportCustomer $model_extension_report_customer
 * @property \Admin\ModelExtensionReportCustomerTransaction $model_extension_report_customer_transaction
 * @property \Admin\ModelExtensionReportMarketing $model_extension_report_marketing
 * @property \Admin\ModelExtensionReportProduct $model_extension_report_product
 * @property \Admin\ModelExtensionReportReturn $model_extension_report_return
 * @property \Admin\ModelExtensionReportSale $model_extension_report_sale
 * @property \Admin\ModelLocalisationCountry|\Catalog\ModelLocalisationCountry $model_localisation_country
 * @property \Admin\ModelLocalisationCurrency|\Catalog\ModelLocalisationCurrency $model_localisation_currency
 * @property \Admin\ModelLocalisationGeoZone $model_localisation_geo_zone
 * @property \Admin\ModelLocalisationLanguage|\Catalog\ModelLocalisationLanguage $model_localisation_language
 * @property \Admin\ModelLocalisationLengthClass $model_localisation_length_class
 * @property \Admin\ModelLocalisationLocation|\Catalog\ModelLocalisationLocation $model_localisation_location
 * @property \Admin\ModelLocalisationOrderStatus|\Catalog\ModelLocalisationOrderStatus $model_localisation_order_status
 * @property \Admin\ModelLocalisationReturnAction $model_localisation_return_action
 * @property \Admin\ModelLocalisationReturnReason|\Catalog\ModelLocalisationReturnReason $model_localisation_return_reason
 * @property \Admin\ModelLocalisationReturnStatus $model_localisation_return_status
 * @property \Admin\ModelLocalisationStockStatus $model_localisation_stock_status
 * @property \Admin\ModelLocalisationTaxClass $model_localisation_tax_class
 * @property \Admin\ModelLocalisationTaxRate $model_localisation_tax_rate
 * @property \Admin\ModelLocalisationWeightClass $model_localisation_weight_class
 * @property \Admin\ModelLocalisationZone|\Catalog\ModelLocalisationZone $model_localisation_zone
 * @property \Admin\ModelMarketingCoupon $model_marketing_coupon
 * @property \Admin\ModelMarketingMarketing $model_marketing_marketing
 * @property \Admin\ModelReportOnline $model_report_online
 * @property \Admin\ModelReportStatistics|\Catalog\ModelReportStatistics $model_report_statistics
 * @property \Admin\ModelSaleOrder $model_sale_order
 * @property \Admin\ModelSaleRecurring $model_sale_recurring
 * @property \Admin\ModelSaleReturn $model_sale_return
 * @property \Admin\ModelSaleVoucher $model_sale_voucher
 * @property \Admin\ModelSaleVoucherTheme $model_sale_voucher_theme
 * @property \Admin\ModelSettingEvent|\Catalog\ModelSettingEvent $model_setting_event
 * @property \Admin\ModelSettingExtension|\Catalog\ModelSettingExtension $model_setting_extension
 * @property \Admin\ModelSettingModification $model_setting_modification
 * @property \Admin\ModelSettingModule|\Catalog\ModelSettingModule $model_setting_module
 * @property \Admin\ModelSettingSetting|\Catalog\ModelSettingSetting $model_setting_setting
 * @property \Admin\ModelSettingStore|\Catalog\ModelSettingStore $model_setting_store
 * @property \Admin\ModelToolBackup $model_tool_backup
 * @property \Admin\ModelToolImage|\Catalog\ModelToolImage $model_tool_image
 * @property \Admin\ModelToolUpload|\Catalog\ModelToolUpload $model_tool_upload
 * @property \Admin\ModelUserApi $model_user_api
 * @property \Admin\ModelUserUser $model_user_user
 * @property \Admin\ModelUserUserGroup $model_user_user_group
 * @property \Catalog\ModelAccountActivity $model_account_activity
 * @property \Catalog\ModelAccountAddress $model_account_address
 * @property \Catalog\ModelAccountApi $model_account_api
 * @property \Catalog\ModelAccountCustomField $model_account_custom_field
 * @property \Catalog\ModelAccountCustomer $model_account_customer
 * @property \Catalog\ModelAccountCustomerGroup $model_account_customer_group
 * @property \Catalog\ModelAccountDownload $model_account_download
 * @property \Catalog\ModelAccountOrder $model_account_order
 * @property \Catalog\ModelAccountRecurring $model_account_recurring
 * @property \Catalog\ModelAccountReturn $model_account_return
 * @property \Catalog\ModelAccountReward $model_account_reward
 * @property \Catalog\ModelAccountSearch $model_account_search
 * @property \Catalog\ModelAccountTransaction $model_account_transaction
 * @property \Catalog\ModelAccountWishlist $model_account_wishlist
 * @property \Catalog\ModelCheckoutMarketing $model_checkout_marketing
 * @property \Catalog\ModelCheckoutOrder $model_checkout_order
 * @property \Catalog\ModelCheckoutRecurring $model_checkout_recurring
 * @property \Catalog\ModelExtensionCreditCardSquareup $model_extension_credit_card_squareup
 * @property \Catalog\ModelExtensionModuleAmazonLogin $model_extension_module_amazon_login
 * @property \Catalog\ModelExtensionModuleLaybuyLayout $model_extension_module_laybuy_layout
 * @property \Catalog\ModelExtensionPaymentAlipay $model_extension_payment_alipay
 * @property \Catalog\ModelExtensionPaymentAlipayCross $model_extension_payment_alipay_cross
 * @property \Catalog\ModelExtensionPaymentAuthorizenetAim $model_extension_payment_authorizenet_aim
 * @property \Catalog\ModelExtensionPaymentAuthorizenetSim $model_extension_payment_authorizenet_sim
 * @property \Catalog\ModelExtensionPaymentBankTransfer $model_extension_payment_bank_transfer
 * @property \Catalog\ModelExtensionPaymentCheque $model_extension_payment_cheque
 * @property \Catalog\ModelExtensionPaymentCod $model_extension_payment_cod
 * @property \Catalog\ModelExtensionPaymentFreeCheckout $model_extension_payment_free_checkout
 * @property \Catalog\ModelExtensionPaymentKlarnaAccount $model_extension_payment_klarna_account
 * @property \Catalog\ModelExtensionPaymentKlarnaInvoice $model_extension_payment_klarna_invoice
 * @property \Catalog\ModelExtensionPaymentLiqpay $model_extension_payment_liqpay
 * @property \Catalog\ModelExtensionPaymentNochex $model_extension_payment_nochex
 * @property \Catalog\ModelExtensionPaymentPaymate $model_extension_payment_paymate
 * @property \Catalog\ModelExtensionPaymentPaypoint $model_extension_payment_paypoint
 * @property \Catalog\ModelExtensionPaymentPayza $model_extension_payment_payza
 * @property \Catalog\ModelExtensionPaymentPerpetualPayments $model_extension_payment_perpetual_payments
 * @property \Catalog\ModelExtensionPaymentPpPayflow $model_extension_payment_pp_payflow
 * @property \Catalog\ModelExtensionPaymentPpPro $model_extension_payment_pp_pro
 * @property \Catalog\ModelExtensionPaymentPpStandard $model_extension_payment_pp_standard
 * @property \Catalog\ModelExtensionPaymentSagepayUs $model_extension_payment_sagepay_us
 * @property \Catalog\ModelExtensionPaymentSkrill $model_extension_payment_skrill
 * @property \Catalog\ModelExtensionPaymentTwocheckout $model_extension_payment_twocheckout
 * @property \Catalog\ModelExtensionPaymentWebPaymentSoftware $model_extension_payment_web_payment_software
 * @property \Catalog\ModelExtensionPaymentWechatPay $model_extension_payment_wechat_pay
 * @property \Catalog\ModelExtensionShippingAuspost $model_extension_shipping_auspost
 * @property \Catalog\ModelExtensionShippingEcShip $model_extension_shipping_ec_ship
 * @property \Catalog\ModelExtensionShippingFedex $model_extension_shipping_fedex
 * @property \Catalog\ModelExtensionShippingFlat $model_extension_shipping_flat
 * @property \Catalog\ModelExtensionShippingFree $model_extension_shipping_free
 * @property \Catalog\ModelExtensionShippingItem $model_extension_shipping_item
 * @property \Catalog\ModelExtensionShippingParcelforce48 $model_extension_shipping_parcelforce_48
 * @property \Catalog\ModelExtensionShippingPickup $model_extension_shipping_pickup
 * @property \Catalog\ModelExtensionShippingPilibaba $model_extension_shipping_pilibaba
 * @property \Catalog\ModelExtensionShippingRoyalMail $model_extension_shipping_royal_mail
 * @property \Catalog\ModelExtensionShippingUps $model_extension_shipping_ups
 * @property \Catalog\ModelExtensionShippingUsps $model_extension_shipping_usps
 * @property \Catalog\ModelExtensionShippingWeight $model_extension_shipping_weight
 * @property \Catalog\ModelExtensionTotalCoupon $model_extension_total_coupon
 * @property \Catalog\ModelExtensionTotalCredit $model_extension_total_credit
 * @property \Catalog\ModelExtensionTotalHandling $model_extension_total_handling
 * @property \Catalog\ModelExtensionTotalKlarnaFee $model_extension_total_klarna_fee
 * @property \Catalog\ModelExtensionTotalLowOrderFee $model_extension_total_low_order_fee
 * @property \Catalog\ModelExtensionTotalReward $model_extension_total_reward
 * @property \Catalog\ModelExtensionTotalShipping $model_extension_total_shipping
 * @property \Catalog\ModelExtensionTotalSubTotal $model_extension_total_sub_total
 * @property \Catalog\ModelExtensionTotalTax $model_extension_total_tax
 * @property \Catalog\ModelExtensionTotalTotal $model_extension_total_total
 * @property \Catalog\ModelExtensionTotalVoucher $model_extension_total_voucher
 * @property \Catalog\ModelExtensionTotalVoucherTheme $model_extension_total_voucher_theme
 * @property \Catalog\ModelSettingApi $model_setting_api
 * @property \Catalog\ModelToolOnline $model_tool_online
 */
abstract class AutoCompleteWithModel extends Autocomplete {}